### ISSUE TITLE
TODO: Features

### ISSUE THREAD

**Issue by Justfines** [Tigereye504/chestcavity#2]
- [ ] Rabbit heart - provide speed boost; reduced health, other stats

- [ ] Creeper-derived organ: explodes on some common interaction, some other item determines explosion size
- [ ] Advancements for direction
